### ISSUE TITLE
This request has been blocked, the content must be served over HTTPS

### ISSUE THREAD

**Issue by ph00k** [idempiere/idempiere-docker#6]
installed docker default localhost:8080/webui/ returns 
This request has been blocked, the content must be served over HTTPS
if i go to localhost:8443 This site can’t be reached

**Comment by CarlosRuiz-globalqss** [comment]
That's the expected behavior.

See https://wiki.idempiere.org/en/Migration_Notes#Deprecated_direct_http_usage
